
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/recommendation?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "0527"
    springdoc:
      swagger-ui.path: /swagger-ui.html


  main:
    web-application-type: servlet  # 确保项目是 Web 应用（如果是 REST API）
server:
    port: 8081  # 修改为可用端口
custom:
  message: "Hello, Spring Boot!"

logging:
  level:
    com.zaxxer.hikari: DEBUG

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update # 自动更新数据库表结构
#    show-sql: ${SHOW_SQL:false} # 生产环境中默认关闭 SQL 显示
#  datasource:
#    url: jdbc:mysql://localhost:3306/recommendation_system?useSSL=false&serverTimezone=UTC
#    username: ${DB_USERNAME} # 使用环境变量
#    password: ${DB_PASSWORD} # 使用环境变量
#    hikari:
#      maximum-pool-size: 10 # 设置最大连接数
#      minimum-idle: 5       # 设置最小空闲连接数
#      connection-timeout: 30000 # 连接超时时间 (毫秒)
#      idle-timeout: 600000  # 空闲连接超时时间 (毫秒)
#      max-lifetime: 1800000 # 连接的最大生命周期 (毫秒)
#  mybatis:
#    mapper-locations: classpath:mapper/*.xml
#    type-aliases-package: com.graduation.backend.entity
